env:
  browser: yes
extends: 'eslint:recommended'
rules:
  indent:
    - 'off'
  linebreak-style:
    - warn
    - unix
  no-console:
    - warn
    - allow:
      - warn
  no-shadow:
    - warn
  no-unused-vars:
    - warn
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
